import PDFDocument from 'pdfkit';
import { Parser } from 'json2csv';
import type { Prisma } from '@prisma/client';

// ─── Types ─────────────────────────────────────────────────────────────────
export interface WeeklySummaryData {
  businessName: string;
  weekStart: Date;
  weekEnd: Date;
  revenue: number;
  newBids: number;
  signedBids: number;
  activeJobs: number;
  completedJobs: number;
  newLeads: number;
  overdueInvoices: number;
  topJobs: Array<{ title: string; revenue: number; margin: number }>;
}

export interface ProfitabilityCsvRow {
  jobTitle: string;
  completedAt: string;
  totalSqFt: number;
  revenue: number;
  cost: number;
  margin: number;
  actualHours: number;
  coatingSystem: string;
}

// ─── Weekly PDF Summary ────────────────────────────────────────────────────
export async function generateWeeklySummaryPdf(data: WeeklySummaryData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const primary = '#0D54A4';
    const gray = '#64748B';
    const lightGray = '#F1F5F9';
    const weekLabel = `${fmtDate(data.weekStart)} – ${fmtDate(data.weekEnd)}`;

    // ── Header bar ──────────────────────────────────────────────────────────
    doc.rect(0, 0, 612, 100).fill(primary);
    doc.fillColor('#FFFFFF').fontSize(22).font('Helvetica-Bold')
       .text(data.businessName, 50, 28);
    doc.fontSize(11).font('Helvetica')
       .text('Weekly Business Summary', 50, 56);
    doc.text(weekLabel, 50, 72);

    doc.fillColor('#000000');
    let y = 120;

    // ── KPI Grid ────────────────────────────────────────────────────────────
    const kpis = [
      { label: 'Revenue', value: `$${fmtMoney(data.revenue)}` },
      { label: 'New Bids', value: String(data.newBids) },
      { label: 'Signed Bids', value: String(data.signedBids) },
      { label: 'Active Jobs', value: String(data.activeJobs) },
      { label: 'Completed Jobs', value: String(data.completedJobs) },
      { label: 'New Leads', value: String(data.newLeads) },
    ];

    const cardW = 150;
    const cardH = 64;
    const cols = 3;
    kpis.forEach((kpi, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = 50 + col * (cardW + 14);
      const cy = y + row * (cardH + 10);
      doc.rect(x, cy, cardW, cardH).fill(lightGray);
      doc.fillColor(gray).fontSize(9).font('Helvetica')
         .text(kpi.label.toUpperCase(), x + 10, cy + 10);
      doc.fillColor(primary).fontSize(20).font('Helvetica-Bold')
         .text(kpi.value, x + 10, cy + 26);
      doc.fillColor('#000');
    });

    y += 2 * (cardH + 10) + 24;

    if (data.overdueInvoices > 0) {
      doc.rect(50, y, 512, 32).fill('#FEF2F2');
      doc.fillColor('#DC2626').fontSize(11).font('Helvetica-Bold')
         .text(`⚠  ${data.overdueInvoices} overdue invoice${data.overdueInvoices > 1 ? 's' : ''} require attention`, 64, y + 10);
      doc.fillColor('#000');
      y += 46;
    }

    // ── Top Jobs Table ───────────────────────────────────────────────────────
    if (data.topJobs.length > 0) {
      doc.fontSize(13).font('Helvetica-Bold').text('Top Jobs This Week', 50, y);
      y += 18;
      doc.rect(50, y, 512, 24).fill(primary);
      doc.fillColor('#FFF').fontSize(9).font('Helvetica-Bold')
         .text('JOB', 60, y + 8)
         .text('REVENUE', 300, y + 8)
         .text('MARGIN', 420, y + 8);
      doc.fillColor('#000');
      y += 24;

      data.topJobs.forEach((job, i) => {
        const bg = i % 2 === 0 ? '#FFFFFF' : lightGray;
        doc.rect(50, y, 512, 22).fill(bg);
        doc.fillColor('#000').fontSize(9).font('Helvetica')
           .text(job.title.slice(0, 50), 60, y + 7)
           .text(`$${fmtMoney(job.revenue)}`, 300, y + 7)
           .text(`${job.margin.toFixed(1)}%`, 420, y + 7);
        y += 22;
      });
    }

    // ── Footer ───────────────────────────────────────────────────────────────
    doc.rect(0, 740, 612, 52).fill(lightGray);
    doc.fillColor(gray).fontSize(8).font('Helvetica')
       .text(`Generated by EpoxyBidPro · ${new Date().toLocaleDateString()}`, 50, 752, { align: 'center', width: 512 });

    doc.end();
  });
}

// ─── Profitability CSV ────────────────────────────────────────────────────
export function generateProfitabilityCsv(rows: ProfitabilityCsvRow[]): string {
  const fields = [
    'jobTitle', 'completedAt', 'totalSqFt',
    'revenue', 'cost', 'margin', 'actualHours', 'coatingSystem',
  ];
  const parser = new Parser({ fields });
  return parser.parse(rows);
}

// ─── Revenue CSV ──────────────────────────────────────────────────────────
export function generateRevenueCsv(rows: Array<{ date: string; amount: number; method: string }>): string {
  const parser = new Parser({ fields: ['date', 'amount', 'method'] });
  return parser.parse(rows);
}

// ─── Helpers ─────────────────────────────────────────────────────────────
function fmtMoney(n: number): string {
  return n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function fmtDate(d: Date): string {
  return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}
